INSERT INTO `org` (`orgName`, `website`) VALUES ('Truong Dai Hoc Cong Nghe Thong Tin', 'uit.edu.vn');
INSERT INTO `org` (`orgName`, `website`) VALUES ('Truong Dai Hoc Quoc Te', 'www.hcmiu.edu.vn');
INSERT INTO `org` (`orgName`, `website`) VALUES ('Truong Dai Hoc Khoa Hoc Tu Nhien', 'www.hcmus.edu.vn');
INSERT INTO `org` (`orgName`, `website`) VALUES ('Truong Dai Hoc Bach Khoa', 'www.hcmut.edu.vn');
INSERT INTO `org` (`orgName`, `website`) VALUES ('Truong Dai Hoc Su Pham', 'www.hcmup.edu.vn');
INSERT INTO `org` (`orgName`, `website`) VALUES ('Truong Dai Hoc Su Pham Ky Thuat', 'www.hcmute.edu.vn');
INSERT INTO `org` (`orgName`, `website`) VALUES ('Truong Dai Hoc Cong Nghiep', 'www.hui.edu.vn');
INSERT INTO `org` (`orgName`, `website`) VALUES ('Truong Dai Hoc Hoa Sen', 'www.hoasen.edu.vn');
INSERT INTO `org` (`orgName`, `website`) VALUES ('Truong Dai Hoc Ky Thuat Cong Nghe', 'www.hutech.edu.vn');
INSERT INTO `org` (`orgName`, `website`) VALUES ('Truong Dai Hoc FPT', 'www.fpt.edu.vn');
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Thanh Hieu', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Van Minh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Van Thanh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Cao Thi Kim Tuyen', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Cao Thi Nhan', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dam Quang Hong Hai', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dinh Dien', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dinh Khac Quyen', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dinh Nguyen Anh Dung', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Phuc', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Thi Minh Phung', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Thi Thanh Tuyen', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Van Nhon', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Duong Khai Phong', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Duong Tan Thanh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Duong Ton Dam', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ho Thi Kim Hoang', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ho Tran Nhat Thuy', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Hoang Van Kiem', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Huu Viet', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Ngoc Tin', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Lam Duc Khai', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Bao Uyen', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Duc Thang', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Hoai Nghia', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Hoang Tuan', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Manh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Lu Nhat Vinh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Luong Ngoc Khanh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Mai Tien Dung', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Mai Xuan Hung', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Han Chieu', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Thanh Hung', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Tuan Kiet', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Anh Tuan', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Dang Khoa', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Ðinh Hien', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Dinh Loan Phuong', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Dinh Quyen', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Dinh Thuan', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Duc Thang', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Duy', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Hoang Tien', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Hoang Tu Anh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Huu Thuong', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Phi Khu', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tat Bao Thien', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thang', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Kim Phung', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Thanh Truc', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thuy Ngoc', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tien Long', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tra Linh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Trac Thuc', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tran Minh Khue', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tuan Dang', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Loi', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Toan', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Xanh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Thi Vuong', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Xuan Khanh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Hoang Chuong', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Nguyen Thuy An', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Nguyet Minh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Quoc Huy', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Trung Hieu', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Thai Bao Tran', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Thai Hai Duong', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Thieu Xuan Khanh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('To Nguyen Nhat Quang', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Anh Dung', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Ba Nhiem', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Thi Nhu Nguyet', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Vinh Phuoc', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Trinh Minh Tuan', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Trinh Quoc Son', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Truong Hai Bang', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Truong Thu Thuy', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo The Dan', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Van Khang', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Duc Khanh', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Duc Lung', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Hai Quan', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Thanh Nguyen', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Tri Dung', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Van Khiet', 1);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Bach Dang', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Hoang Than Anh Tuan', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Kha Tu', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Hai Duong', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Thanh Son', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ly Tu Nga', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Duc Cuong', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Sinh', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Van Hau', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Viet Hoang', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Manh Ha', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Duy Khoi', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Zhivko Nedev', 2);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Tan Loc', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Tien Len', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Chu Tat Bich San', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dang Thi Thanh Nguyen', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dao Anh Tuan', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dao Anh Vu', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dinh Ba Thang', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dinh Ba Tien', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Lenh Hung Son', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Xuan Quang', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dong Thi Bich Thuy', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Duong Anh Duc', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ho Tuan Thanh', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Trung Dong', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Lam Quang Vu', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Lam Xuan Nhat', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Dinh Duy', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Hoai Bac', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Hoang Thai', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Khac Nhien An', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Thuy Anh', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Xuan Dinh', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ly Quoc Ngoc', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Mai Anh Tuan', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Mai Van Cuong', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Ba Nam Phuong', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Huy Bien', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Ngoc Dang Khoa', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Dinh Thuc', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Dong Ha', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Duc Hoang Ha', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Duc Huy', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Hoang Anh', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Huy Khanh', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Khac Huy', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Luu Thuy Ngan', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Minh Huy', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Pham Phuong Nam', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Son Hoang Quoc', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tan Tran Minh', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Bich', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tien Huy', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tran Minh Thu', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tri Tuan', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Khiet', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Vu', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Hoang Hai', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Minh Tuan', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Nam Trung', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Tu San', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Thai Hung Van', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Cong Danh', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Dan Thu', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Duc Duan', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Duy Hoang', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Duy Thao', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Hanh Nhi', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Le Hong Du', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Minh Triet', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Thai Son', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Thi Bich Hanh', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Van Quy', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Truong Phuoc Loc', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Van Chi Nam', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Duc Khanh', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Huu Phuc', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Hai Quan', 3);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Hoai Thang', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Van Hieu', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Cao Hoang Tru', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dang Tran Khanh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dinh Duc Anh Vu', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Doan Minh Vung', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Doan Nguyen Hai', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Doan Viet Hung', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Duong Ngoc Hieu', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Duong Nguyen Vu', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Duong Tuan Anh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ha Hoai Phuong', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ho Quoc Thuan', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ho Tran Linh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ho Van Quan', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Hoang Duc Minh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Ngoc Thanh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Tan Dat', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Lam Son', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Minh Vu', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Nam Hien', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Ngoc Minh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Quang Loc', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Thanh Sach', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Trung Quan', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Luong Thu Thuy', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ly Hoang Hai', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Huy Hoang', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Cao Dat', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Cao Tri', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Hua Phung', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Huu Hai', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Lu Dang Khoa', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Manh Tho', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Ngo Bao Tran', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Quang Hung', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Quoc Tuan', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Quoc Viet Hung', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thanh Son', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thanh Tung', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Truc Vien', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Trung Truc', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tuan Anh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Doan', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Hiep', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Minh Man', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Viet Hung', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Xuan Minh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Ba Ha', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Hoang Anh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Quoc Cuong', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Dinh Khoi', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Dinh Mai', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Dinh The Duy', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Thi Thanh Huyen ', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Thi Tuoi', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Truong Khoa', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phung Huu Phu', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Quan Thanh Tho', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Thoai Nam', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Dang Khoa', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Hoang Ha', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Minh Quang', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Ngoc Minh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Ngoc Thinh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Nguyen Hoang Huy', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Quang', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Van Hoai', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Truong Hong Linh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Hoang Tam', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Le Hung', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Ngoc Vinh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Quang Hieu', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Tuan Thanh', 4);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Au Buu Long', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ho Thi Ngoc Thanh', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Tan Dat', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Duc Long', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Minh Triet', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Minh Trung', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Luong Tran Hy Hien', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Quoc Viet', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Dang Kim Khanh', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Do Thai Nguyen', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Huu Thong', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Khac Van', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Quang Tan', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tan Khoa', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thanh Phuoc', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Ngoc Hoa', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thuy Ngoc', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tran Phi Phuong', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Viet Hung', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Duc Tam', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Huu Quoc Thu', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Phuoc Tuan', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Son Hai', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Thi Thuy Tien', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Trinh Huy Hoang', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Phuong Nguyen', 5);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dang Thanh Dung', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dang Thi Kim Giao', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dang Truong Son', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dinh Cong Doan', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Hoang Long', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Nguyen Chinh', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Ton Nghia', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Trung Hieu', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Van Vinh', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Vinh Thinh', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Mai Tuan Khoi', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Cong Thuong', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Dang Quang', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Hoai Le', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Huu Trung', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Minh Dao', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Phuong', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Quang Ngoc', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thanh Son', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thanh Tuan', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Thanh Van', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thien Bao', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tran Thi Van', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Long', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phung Quang Ngoc', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Quach Dinh Hoang', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Cong Tu', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Nhat Quang', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Tien Duc', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Truong Thi Ngoc Phuong', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tu Tuyet Hong', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Kim Hanh', 6);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Cong Danh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Cong Truong', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Chau Thi Bao Ha', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dang Thanh Binh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dang Thanh Minh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dang Thi Phuc', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dang Thi Thu Ha', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dao Thi Cam Hang', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Cong Thanh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Ha Phuong', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Thi Kim Niet', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Duong Tien Lam', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Giang Thanh Tron', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ho Dac Quan', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Hoang Dinh Hanh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Hoang Thi Thanh Ngoc', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Thai Hoc', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Trung Hieu', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Vu Nhu Lien', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Ngoc Son', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Ngoc Tan', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Ngoc Tien', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Nhat Duy', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Thuy Trang', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Trong Ngoc', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Mai Xuan Phu', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Hoa', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Huu Tinh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Minh Hai', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Nam', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Ngoc Dung', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Nho Dung', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Nhu Hoa', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Phan Trung', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Phuc Hung', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Quang Trung', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Quoc Dinh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thanh Thai', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Cam Huong', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Hanh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Hien Trang', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Hoang Khanh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Hong Luong', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Hong Minh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Minh Hieu', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi My Linh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Phi Loan', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Phuong Giang', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Thanh Binh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Truc Ly', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tran Anh Tuan', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tran Cao Tan Khoa', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Hung', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Quang', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Tan', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Thang', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Quang Tri', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Si Quan', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Thanh Hung', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Thanh Mai', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Thi Hong', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Thi Thiet', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Thi Xuan Dieu', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Van Chung', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Viet Kha', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Xuan Kien', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ta Duy Cong Chien', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Thai Le My Loan', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ton Long Phuoc', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Dac Phien', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Duy Thanh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Thi Anh Thi', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Thi Kim Chi', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Thi Ngoc Hoa', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Thi Nhan Ai', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Van Vinh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Truong Khac Tung', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tu Thi Hong Nhung', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tu Thi Xuan Hien', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Van Phu Hoi', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Cong Minh', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Ngoc Tan Phuoc', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Quang Hoang Khang', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Thi Thanh Van', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Thi Xuan Thieu', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Van Hai', 7);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Xuan Huy', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Cao Van Tho', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dinh Ngoc Luyen', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Trong Danh', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ho Hai Van', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Tan Phuoc', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Anh Vu', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Thanh Tung', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Luu Thanh Tra', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Hung Dung', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Viet Phuong', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Anh Tuan', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Ba Trung', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Huu Phan Hoang Ho', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Huu Phat', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Kim Long', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Ngoc Nhu Hang', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Ngoc Tu', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Phuong Hoang', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Phuong Lien', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Thanh', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Thanh Tam', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Thanh Thanh', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Trieu Phuong', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Trung Lap', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Son', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Vu Ngoc Tung', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Thi Kim Ngon', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Thi Thanh Tam', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Dinh The Huan', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Trang Hong Son', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Hoang Hai', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Thi Thu Ha', 8);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Cao Tung Anh', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dinh Thi Luong', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Cong Khanh', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Manh Hai', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Mau Gia Bao', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Thi Hong Ngoc', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Trung Hieu', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Mai Ngoc Thu', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen An Khuong', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Cao Tri', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Chanh Thanh', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Duc Quang', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Ha Giang', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Hoang Nam', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thanh Giang', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thuy Loan', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Thi Lan Anh', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Ho Le Phuong Dan', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Truong Thi Minh Chau', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Van Nhu Bich B', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Van Thi Thien Trang', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Van Thien Hoang', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Dinh Bay', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vo Hoang Khang', 9);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bach Thu Quyen', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Anh Bao', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Phuong Anh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Phuong Nhung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Quang Vinh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Sy Nguyen', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Bui Thi Hong Lien', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Cao Le Thi Khanh Ngoc', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dang Dang Khoa', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dang Sy Hai', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dang Thi Thanh Hoa B', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dao Duy Cuong', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dao Ngoc Anh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dao Trong Duy', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dinh Ngoc Anh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dinh Thanh Hung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Dinh Thi Lan', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Quoc Binh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Do Thanh Nam', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Duong Trong Phu Son', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Duong Trong Tan', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Giang Vy Hung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ha Dung Hiep', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ho Hoan Kiem', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Hoang A Na', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Hoang Anh Minh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Hoang Duc Quang', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Hoang Thi Hai Yen', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Hoang Xuan Bach', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Anh Dung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Huynh Van Bay', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Kieu Trong Khanh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('La Ngoc Quang', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Duy Nam', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Gia Minh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Ha Duc', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Hai Nam', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Hong Hai', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Mong Thuy', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Thanh Hai', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Thanh Nhan', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Thanh Son', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le The Hung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Thi Ngoc Quyen', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Thi Thoa', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Van Hoc', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Le Xuan Hoang', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Luc Duc Thanh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Luong Hong Hai', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Mario Pham', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Phuoc Nguyen', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo The Tuan', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Tieu Huy', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ngo Xuan Giap', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Bao Huynh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Cuong', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Duy Dung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Hoai Vu', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Hoang Cong', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Huong Tra', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Huu Luong Tu', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Khac Quyen', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Khai Hoan', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Khanh Trinh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Mai Anh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Manh Cuong', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Manh Dung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Minh Son', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Ngoc Anh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Nhu Anh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Quang Hoa', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Quynh Chi', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tat Trung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thanh Lam', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thanh Phuong', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thanh Vinh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Hanh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Hong Lien Minh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Huong Thom', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Kieu Thanh Thuy', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Minh Hai', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Minh Hue', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi My Chi', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Quynh Mai', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Thi Thanh Binh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tho Khoi', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Tran Thanh Binh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Trung Hieu', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Trung Kien', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Anh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Binh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Dong', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Van Sang', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Viet Anh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Nguyen Viet Hung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Anh Doi', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Cong Thanh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Hung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Huu Tung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Le Duc Ngan', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham My Ngoc', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Thanh Trung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Thi Minh Hien', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Tuan Anh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Van Dung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Pham Viet Nga', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Duy Hung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Minh Tam', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Thi Hai Ha', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Trung Diep', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phan Truong Lam', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phung Thanh Xuan', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Phung Thi Phuong Thuy', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Quach Ngoc Xuan', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Ta Tran Minh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Than Thi Ngoc Van', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Than Van Su', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Binh Duong', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Dinh Tri', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Do Luong', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Huu Cong', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Ngoc Trung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Nguyen Ngoc', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Phuoc Sinh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Thanh Trung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Thanh Trung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Thi Le', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Thi Van', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Vinh Thu', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Tran Xuan Lam', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Truong Kieu Linh', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Van Thi Hong Phuc', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Van Thi Kim Ngan', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Dang Khoa', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Hong Dung', 10);
INSERT INTO `author` (`authorName`, `idOrg`) VALUES ('Vu Tran Lam', 10);