/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CSPublicationCrawlerSettingView.java
 *
 * Created on 10-08-2011, 02:29:48
 */
package uit.tkorg.cspublicationcrawler.gui;

import javax.swing.JFrame;


/**
 *
 * @author v-huongt
 */
public class CSPublicationCrawlerSettingView extends javax.swing.JFrame {

    /** Creates new form CSPublicationCrawlerSettingView */
    public CSPublicationCrawlerSettingView() {
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingTabbedPane = new javax.swing.JTabbedPane();
        dbconnectorPanel = new javax.swing.JPanel();
        urlLabel = new javax.swing.JLabel();
        urlTextField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        dbnameLabel = new javax.swing.JLabel();
        dbnameTextField = new javax.swing.JTextField();
        testconnectionButton = new javax.swing.JButton();
        outputLabel = new javax.swing.JLabel();
        outputScrollPane = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        schedulePanel = new javax.swing.JPanel();
        fromdateLabel = new javax.swing.JLabel();
        fromdateTextField = new javax.swing.JTextField();
        todateLabel = new javax.swing.JLabel();
        todateTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ondaysLabel = new javax.swing.JLabel();
        monCheckBox = new javax.swing.JCheckBox();
        tueCheckBox = new javax.swing.JCheckBox();
        wedCheckBox = new javax.swing.JCheckBox();
        thuCheckBox = new javax.swing.JCheckBox();
        friCheckBox = new javax.swing.JCheckBox();
        satCheckBox = new javax.swing.JCheckBox();
        sunCheckBox = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        modeLabel = new javax.swing.JLabel();
        timerequestLabel = new javax.swing.JLabel();
        timerequestTextField = new javax.swing.JTextField();
        timeoutLabel = new javax.swing.JLabel();
        secondsLabel = new javax.swing.JLabel();
        timeoutTextField = new javax.swing.JTextField();
        msLabel = new javax.swing.JLabel();
        fromtimeTextField = new javax.swing.JTextField();
        fromtimeLabel = new javax.swing.JLabel();
        totimeTextField = new javax.swing.JTextField();
        totimeLabel = new javax.swing.JLabel();
        dailyrunCheckBox = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        sleepafterLabel = new javax.swing.JLabel();
        sleeprequestTextField = new javax.swing.JTextField();
        requestLabel = new javax.swing.JLabel();
        sleepsecondTextField = new javax.swing.JTextField();
        secondLabel = new javax.swing.JLabel();
        stopafterLabel = new javax.swing.JLabel();
        stoprequestTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        setscheduleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(uit.tkorg.cspublicationcrawler.gui.CSPublicationCrawlerApp.class).getContext().getResourceMap(CSPublicationCrawlerSettingView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        settingTabbedPane.setName("settingTabbedPane"); // NOI18N

        dbconnectorPanel.setName("dbconnectorPanel"); // NOI18N

        urlLabel.setText(resourceMap.getString("urlLabel.text")); // NOI18N
        urlLabel.setName("urlLabel"); // NOI18N

        urlTextField.setText(resourceMap.getString("urlTextField.text")); // NOI18N
        urlTextField.setName("urlTextField"); // NOI18N

        usernameLabel.setText(resourceMap.getString("usernameLabel.text")); // NOI18N
        usernameLabel.setName("usernameLabel"); // NOI18N

        usernameTextField.setName("usernameTextField"); // NOI18N

        passwordLabel.setText(resourceMap.getString("passwordLabel.text")); // NOI18N
        passwordLabel.setName("passwordLabel"); // NOI18N

        passwordTextField.setName("passwordTextField"); // NOI18N

        dbnameLabel.setText(resourceMap.getString("dbnameLabel.text")); // NOI18N
        dbnameLabel.setName("dbnameLabel"); // NOI18N

        dbnameTextField.setName("dbnameTextField"); // NOI18N

        testconnectionButton.setText(resourceMap.getString("testconnectionButton.text")); // NOI18N
        testconnectionButton.setName("testconnectionButton"); // NOI18N

        outputLabel.setText(resourceMap.getString("outputLabel.text")); // NOI18N
        outputLabel.setName("outputLabel"); // NOI18N

        outputScrollPane.setName("outputScrollPane"); // NOI18N

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        outputTextArea.setName("outputTextArea"); // NOI18N
        outputScrollPane.setViewportView(outputTextArea);

        javax.swing.GroupLayout dbconnectorPanelLayout = new javax.swing.GroupLayout(dbconnectorPanel);
        dbconnectorPanel.setLayout(dbconnectorPanelLayout);
        dbconnectorPanelLayout.setHorizontalGroup(
            dbconnectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbconnectorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dbconnectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addGroup(dbconnectorPanelLayout.createSequentialGroup()
                        .addGroup(dbconnectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbnameLabel)
                            .addComponent(usernameLabel)
                            .addComponent(urlLabel))
                        .addGap(18, 18, 18)
                        .addGroup(dbconnectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(urlTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addGroup(dbconnectorPanelLayout.createSequentialGroup()
                                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passwordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addComponent(dbnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)))
                    .addComponent(outputLabel)
                    .addComponent(testconnectionButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        dbconnectorPanelLayout.setVerticalGroup(
            dbconnectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbconnectorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dbconnectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlLabel)
                    .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dbconnectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dbconnectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbnameLabel)
                    .addComponent(dbnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(testconnectionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        settingTabbedPane.addTab(resourceMap.getString("dbconnectorPanel.TabConstraints.tabTitle"), dbconnectorPanel); // NOI18N

        schedulePanel.setName("schedulePanel"); // NOI18N

        fromdateLabel.setText(resourceMap.getString("fromdateLabel.text")); // NOI18N
        fromdateLabel.setName("fromdateLabel"); // NOI18N

        fromdateTextField.setName("fromdateTextField"); // NOI18N

        todateLabel.setText(resourceMap.getString("todateLabel.text")); // NOI18N
        todateLabel.setName("todateLabel"); // NOI18N

        todateTextField.setName("todateTextField"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        ondaysLabel.setText(resourceMap.getString("ondaysLabel.text")); // NOI18N
        ondaysLabel.setName("ondaysLabel"); // NOI18N

        monCheckBox.setText(resourceMap.getString("monCheckBox.text")); // NOI18N
        monCheckBox.setName("monCheckBox"); // NOI18N

        tueCheckBox.setText(resourceMap.getString("tueCheckBox.text")); // NOI18N
        tueCheckBox.setName("tueCheckBox"); // NOI18N

        wedCheckBox.setText(resourceMap.getString("wedCheckBox.text")); // NOI18N
        wedCheckBox.setName("wedCheckBox"); // NOI18N

        thuCheckBox.setText(resourceMap.getString("thuCheckBox.text")); // NOI18N
        thuCheckBox.setName("thuCheckBox"); // NOI18N

        friCheckBox.setText(resourceMap.getString("friCheckBox.text")); // NOI18N
        friCheckBox.setName("friCheckBox"); // NOI18N

        satCheckBox.setText(resourceMap.getString("satCheckBox.text")); // NOI18N
        satCheckBox.setName("satCheckBox"); // NOI18N

        sunCheckBox.setText(resourceMap.getString("sunCheckBox.text")); // NOI18N
        sunCheckBox.setName("sunCheckBox"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        modeLabel.setText(resourceMap.getString("modeLabel.text")); // NOI18N
        modeLabel.setName("modeLabel"); // NOI18N

        timerequestLabel.setText(resourceMap.getString("timerequestLabel.text")); // NOI18N
        timerequestLabel.setName("timerequestLabel"); // NOI18N

        timerequestTextField.setText(resourceMap.getString("timerequestTextField.text")); // NOI18N
        timerequestTextField.setName("timerequestTextField"); // NOI18N

        timeoutLabel.setText(resourceMap.getString("timeoutLabel.text")); // NOI18N
        timeoutLabel.setName("timeoutLabel"); // NOI18N

        secondsLabel.setText(resourceMap.getString("secondsLabel.text")); // NOI18N
        secondsLabel.setName("secondsLabel"); // NOI18N

        timeoutTextField.setName("timeoutTextField"); // NOI18N

        msLabel.setText(resourceMap.getString("msLabel.text")); // NOI18N
        msLabel.setName("msLabel"); // NOI18N

        fromtimeTextField.setName("fromtimeTextField"); // NOI18N

        fromtimeLabel.setText(resourceMap.getString("fromtimeLabel.text")); // NOI18N
        fromtimeLabel.setName("fromtimeLabel"); // NOI18N

        totimeTextField.setName("totimeTextField"); // NOI18N

        totimeLabel.setText(resourceMap.getString("totimeLabel.text")); // NOI18N
        totimeLabel.setName("totimeLabel"); // NOI18N

        dailyrunCheckBox.setText(resourceMap.getString("dailyrunCheckBox.text")); // NOI18N
        dailyrunCheckBox.setName("dailyrunCheckBox"); // NOI18N

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setName("jSeparator3"); // NOI18N

        sleepafterLabel.setText(resourceMap.getString("sleepafterLabel.text")); // NOI18N
        sleepafterLabel.setName("sleepafterLabel"); // NOI18N

        sleeprequestTextField.setText(resourceMap.getString("sleeprequestTextField.text")); // NOI18N
        sleeprequestTextField.setName("sleeprequestTextField"); // NOI18N

        requestLabel.setText(resourceMap.getString("requestLabel.text")); // NOI18N
        requestLabel.setName("requestLabel"); // NOI18N

        sleepsecondTextField.setText(resourceMap.getString("sleepsecondTextField.text")); // NOI18N
        sleepsecondTextField.setName("sleepsecondTextField"); // NOI18N

        secondLabel.setText(resourceMap.getString("secondLabel.text")); // NOI18N
        secondLabel.setName("secondLabel"); // NOI18N

        stopafterLabel.setText(resourceMap.getString("stopafterLabel.text")); // NOI18N
        stopafterLabel.setName("stopafterLabel"); // NOI18N

        stoprequestTextField.setText(resourceMap.getString("stoprequestTextField.text")); // NOI18N
        stoprequestTextField.setName("stoprequestTextField"); // NOI18N

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        setscheduleButton.setText(resourceMap.getString("setscheduleButton.text")); // NOI18N
        setscheduleButton.setName("setscheduleButton"); // NOI18N

        javax.swing.GroupLayout schedulePanelLayout = new javax.swing.GroupLayout(schedulePanel);
        schedulePanel.setLayout(schedulePanelLayout);
        schedulePanelLayout.setHorizontalGroup(
            schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(schedulePanelLayout.createSequentialGroup()
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(schedulePanelLayout.createSequentialGroup()
                                .addComponent(fromdateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(fromdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, schedulePanelLayout.createSequentialGroup()
                                .addComponent(todateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(todateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fromtimeLabel)
                            .addComponent(totimeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromtimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(schedulePanelLayout.createSequentialGroup()
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ondaysLabel)
                            .addComponent(modeLabel))
                        .addGap(26, 26, 26)
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dailyrunCheckBox)
                            .addGroup(schedulePanelLayout.createSequentialGroup()
                                .addComponent(monCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tueCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(wedCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thuCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(friCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(satCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sunCheckBox))))
                    .addGroup(schedulePanelLayout.createSequentialGroup()
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timerequestLabel)
                            .addComponent(timeoutLabel)
                            .addGroup(schedulePanelLayout.createSequentialGroup()
                                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(timeoutTextField)
                                    .addComponent(timerequestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(msLabel)
                                    .addComponent(secondsLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sleepafterLabel)
                                .addComponent(stopafterLabel)
                                .addGroup(schedulePanelLayout.createSequentialGroup()
                                    .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(stoprequestTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, schedulePanelLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(sleeprequestTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                                    .addGap(4, 4, 4)
                                    .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addGroup(schedulePanelLayout.createSequentialGroup()
                                            .addComponent(requestLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(sleepsecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(secondLabel)))))
                            .addComponent(setscheduleButton)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        schedulePanelLayout.setVerticalGroup(
            schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(schedulePanelLayout.createSequentialGroup()
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromdateLabel)
                            .addComponent(fromdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(todateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(todateLabel)))
                    .addGroup(schedulePanelLayout.createSequentialGroup()
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(schedulePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(fromtimeLabel))
                            .addComponent(fromtimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totimeLabel)
                            .addComponent(totimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeLabel)
                    .addComponent(dailyrunCheckBox))
                .addGap(8, 8, 8)
                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ondaysLabel)
                    .addComponent(monCheckBox)
                    .addComponent(tueCheckBox)
                    .addComponent(wedCheckBox)
                    .addComponent(thuCheckBox)
                    .addComponent(friCheckBox)
                    .addComponent(satCheckBox)
                    .addComponent(sunCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(schedulePanelLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(schedulePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timerequestLabel)
                                .addGap(4, 4, 4)
                                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(timerequestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(secondsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(timeoutLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(timeoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(msLabel)))
                            .addGroup(schedulePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(sleepafterLabel)
                                .addGap(2, 2, 2)
                                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sleeprequestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(requestLabel)
                                    .addComponent(sleepsecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(secondLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stopafterLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(stoprequestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55)
                        .addComponent(setscheduleButton))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addContainerGap())
        );

        settingTabbedPane.addTab(resourceMap.getString("schedulePanel.TabConstraints.tabTitle"), schedulePanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(settingTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(settingTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSPublicationCrawlerSettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSPublicationCrawlerSettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSPublicationCrawlerSettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSPublicationCrawlerSettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CSPublicationCrawlerSettingView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox dailyrunCheckBox;
    private javax.swing.JPanel dbconnectorPanel;
    private javax.swing.JLabel dbnameLabel;
    private javax.swing.JTextField dbnameTextField;
    private javax.swing.JCheckBox friCheckBox;
    private javax.swing.JLabel fromdateLabel;
    private javax.swing.JTextField fromdateTextField;
    private javax.swing.JLabel fromtimeLabel;
    private javax.swing.JTextField fromtimeTextField;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JCheckBox monCheckBox;
    private javax.swing.JLabel msLabel;
    private javax.swing.JLabel ondaysLabel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JScrollPane outputScrollPane;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel requestLabel;
    private javax.swing.JCheckBox satCheckBox;
    private javax.swing.JPanel schedulePanel;
    private javax.swing.JLabel secondLabel;
    private javax.swing.JLabel secondsLabel;
    private javax.swing.JButton setscheduleButton;
    private javax.swing.JTabbedPane settingTabbedPane;
    private javax.swing.JLabel sleepafterLabel;
    private javax.swing.JTextField sleeprequestTextField;
    private javax.swing.JTextField sleepsecondTextField;
    private javax.swing.JLabel stopafterLabel;
    private javax.swing.JTextField stoprequestTextField;
    private javax.swing.JCheckBox sunCheckBox;
    private javax.swing.JButton testconnectionButton;
    private javax.swing.JCheckBox thuCheckBox;
    private javax.swing.JLabel timeoutLabel;
    private javax.swing.JTextField timeoutTextField;
    private javax.swing.JLabel timerequestLabel;
    private javax.swing.JTextField timerequestTextField;
    private javax.swing.JLabel todateLabel;
    private javax.swing.JTextField todateTextField;
    private javax.swing.JLabel totimeLabel;
    private javax.swing.JTextField totimeTextField;
    private javax.swing.JCheckBox tueCheckBox;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField urlTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JCheckBox wedCheckBox;
    // End of variables declaration//GEN-END:variables
}
